### PR TITLE
extensible 0.6.1 マイグレーションガイド

### PR DESCRIPTION
**Pull request by waddlaw**

### CODE REVIEW

**Comment by waddlaw** [comment]
https://circleci.com/gh/e-bigmoon/haskell-blog/2614/artifacts/0/root/haskell-blog/_site/index.html

**Comment by waddlaw** [comment]
https://circleci.com/gh/e-bigmoon/haskell-blog/2618/artifacts/0/root/haskell-blog/_site/index.html

**Comment by waddlaw** [comment]
https://circleci.com/gh/e-bigmoon/haskell-blog/2623/artifacts/0/root/haskell-blog/_site/index.html

**Comment by waddlaw** [comment]
https://circleci.com/gh/e-bigmoon/haskell-blog/2628/artifacts/0/root/haskell-blog/_site/index.html

**Comment by waddlaw** [comment]
https://circleci.com/gh/e-bigmoon/haskell-blog/2637/artifacts/0/root/haskell-blog/_site/index.html

**Comment by fumieval** [comment]
LGTM

**Pull request merged**
